%%
%% src/leo_nlm_proto4.hrl was generated by erpcgen (do not edit)
%%
-define(NLM_PROG, 100021).
-define(NLM4_VERS, 4).
-define(MAXNETOBJ_SZ, 1024).
-define(LM_MAXNAMELEN, 1025).
-define(LM_MAXSTRLEN, 1024).
