%%
%% src/leo_nfs_proto3.hrl was generated by erpcgen (do not edit)
%%
-define(NFS3_PROGRAM, 100003).
-define(NFS_V3, 3).
-define(FSF3_CANSETTIME, 16).
-define(FSF3_HOMOGENEOUS, 8).
-define(FSF3_SYMLINK, 2).
-define(FSF3_LINK, 1).
-define(ACCESS3_EXECUTE, 32).
-define(ACCESS3_DELETE, 16).
-define(ACCESS3_EXTEND, 8).
-define(ACCESS3_MODIFY, 4).
-define(ACCESS3_LOOKUP, 2).
-define(ACCESS3_READ, 1).
-define(NFS3_WRITEVERFSIZE, 8).
-define(NFS3_CREATEVERFSIZE, 8).
-define(NFS3_COOKIEVERFSIZE, 8).
-define(NFS3_FHSIZE, 64).
