##======================================================================
## LeoFS - Manager Configuration (SLAVE) - Docker
##======================================================================
## --------------------------------------------------------------------
## MANAGER
## --------------------------------------------------------------------
## Partner of manager's alias
manager.partner = manager_0@leo_manager_0

## Manager-console accepatable ip address
console.bind_address = 0.0.0.0

## Manager-console accepatable port number
console.port.cui  = 10012
console.port.json = 10022

## Manager-console's number of acceptors
console.acceptors.cui = 3
console.acceptors.json = 16

## # of histories to display at once
console.histories.num_of_display = 200

## --------------------------------------------------------------------
## MANAGER - Mnesia
## --------------------------------------------------------------------
## Mnesia dir
mnesia.dir = ./work/mnesia/leo_manager_1

## The write threshold for transaction log dumps
mnesia.dump_log_write_threshold = 50000

## Controls how often disc_copies tables are dumped from memory
mnesia.dc_dump_limit = 40

## --------------------------------------------------------------------
## RPC
## --------------------------------------------------------------------
## RPC-Server's acceptors
rpc.server.acceptors = 16

## RPC-Server's listening port number
rpc.server.listen_port = 13076

## RPC-Server's listening timeout
rpc.server.listen_timeout = 5000

## RPC-Client's size of connection pool
rpc.client.connection_pool_size = 16

## RPC-Client's size of connection buffer
rpc.client.connection_buffer_size = 16

##======================================================================
## For vm.args
##======================================================================
## Name of the LeoFS's manager node
nodename = manager_1@leo_manager_1

## Cookie for distributed node communication.
distributed_cookie = 401321b4

## Enable kernel poll
erlang.kernel_poll = true

## Number of async threads
erlang.asyc_threads = 32

## Increase number of concurrent ports/sockets
erlang.max_ports = 64000

## Set the location of crash dumps
erlang.crash_dump = ./log/erl_crash.dump

## Raise the ETS table limit
erlang.max_ets_tables = 256000

## Enable SMP
erlang.smp = enable

## Raise the default erlang process limit
process_limit = 1048576
