#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et
#======================================================================
#
# LeoFS
#
# Copyright (c) 2012-2015 Rakuten, Inc.
#
# This file is provided to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#======================================================================
bold=`tput bold`
normal=`tput sgr0`

SCRIPT=`basename $0`
OS=`uname -s`

##
## Output text
##
output() {
    case $OS in
        FreeBSD)
            echo -e "$1"
            ;;
        SunOS)
            echo -e "$1"
            ;;
        *)
            echo "$1"
    esac
}

##
## Usage of the script
##
usage() {
    output "usage: ${bold}$SCRIPT${normal} [--help]"
    output "       ${bold}$SCRIPT${normal} -h <hostname> -n <leo_node_name> -k <kind_of_node>"
    output "                 [-snmp_ip <snmp-ip>] [-snmp_port <snmp-port>]"
    output "                 [-influx_ip <influxdb-ip>] [-influx_port <influxdb-port>]"
    output "                 [-data_source <datasource-name>]"
    output "                 [-schema12]"
    output "                 [-api]"
    output ""
    output "       ${bold}description of the parameters:${normal}"
    output "         * <kind_of_node>: [storage | gateway | manager]"
    output ""
}

##
## Generate a configuration file
##
if [ $# -lt 3 ]; then
    usage
    exit 1
fi

SNMP_IP="127.0.0.1"
SNMP_PORT=4010
INFLUXDB_IP="localhost"
INFLUXDB_PORT=8086
DATA_SOURCE=null
TEMPLATE_DIR="template"
enabled_api=false

while test -n "$1"; do
    case "$1" in
        --help)
            usage | less -r
            exit 0
            ;;
        -h)
            GEN_CONF_HOST="$2"
            shift
            ;;
        -n)
            GEN_CONF_NODE="$2"
            shift
            ;;
        -k)
            GEN_CONF_KIND="$2"
            shift
            ;;
        -snmp_ip)
            SNMP_IP="$2"
            shift
            ;;
        -snmp_port)
            SNMP_PORT="$2"
            shift
            ;;
        -influx_ip)
            INFLUXDB_IP="$2"
            shift
            ;;
        -influx_port)
            INFLUXDB_PORT="$2"
            shift
            ;;
        -data_source)
            DATA_SOURCE="\"$2\""
            shift
            ;;
        -schema12)
            TEMPLATE_DIR="template_12"
            ;;
        -api)
            enabled_api=true
            ;;
        *)
            break
    esac
    shift
done

if test "${GEN_CONF_HOST}" = ""; then
    usage
    exit 1
fi
if test "${GEN_CONF_NODE}" = ""; then
    usage
    exit 1
fi
if test "${GEN_CONF_KIND}" = ""; then
    usage
    exit 1
fi

GEN_CONF_NODE_1=`echo "$GEN_CONF_NODE" | sed s/@/_at_/g`
FILENAME_GRAFANA="${GEN_CONF_NODE_1}.grafana"
FILENAME_TELEGRAF="${GEN_CONF_NODE_1}.telegraf"

case $GEN_CONF_KIND in
    storage)
        TEMPLATE_GRAFANA="$TEMPLATE_DIR/leofs-storage.grafana"
        TEMPLATE_TELEGRAF="$TEMPLATE_DIR/leofs-storage.telegraf"
        ;;
    gateway)
        TEMPLATE_GRAFANA="$TEMPLATE_DIR/leofs-gateway.grafana"
        TEMPLATE_TELEGRAF="$TEMPLATE_DIR/leofs-gateway.telegraf"
        ;;
    manager)
        TEMPLATE_GRAFANA="$TEMPLATE_DIR/leofs-manager.grafana"
        TEMPLATE_TELEGRAF="$TEMPLATE_DIR/leofs-manager.telegraf"
        ;;
    *)
        usage
        exit 1
esac

cat $TEMPLATE_GRAFANA | \
    sed -e "s/<TITLE>/${GEN_CONF_NODE} Dashboard/g"\
        -e "s/<LEO-NODE-NAME>/${GEN_CONF_NODE}/g" \
        -e "s/<HOSTNAME>/${GEN_CONF_HOST}/g"\
        -e "s/<DATA_SOURCE>/${DATA_SOURCE}/g"\
        > $FILENAME_GRAFANA

if $enabled_api ; then
  sed -i -e "2i \"dashboard\": {" $FILENAME_GRAFANA
  sed -i -e "$ i },\n\"overwrite\":false" $FILENAME_GRAFANA
fi

cat $TEMPLATE_TELEGRAF | \
    sed -e "s/<SNMP_IP>/${SNMP_IP}/g" \
        -e "s/<SNMP_PORT>/${SNMP_PORT}/g"\
        -e "s/<INFLUXDB_IP>/${INFLUXDB_IP}/g" \
        -e "s/<INFLUXDB_PORT>/${INFLUXDB_PORT}/g"\
        > $FILENAME_TELEGRAF

echo "DONE:"
echo "  - ${FILENAME_GRAFANA}"
echo "  - ${FILENAME_TELEGRAF}"
